# Generated by Django 4.2.14 on 2024-07-12 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('orig_lan', models.CharField(max_length=2)),
                ('info', models.TextField()),
                ('pub_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CreditType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('info', models.TextField()),
                ('premiere', models.IntegerField()),
                ('runtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WikiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('info', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('wtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wikitype')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('info', models.TextField()),
                ('wtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wikitype')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_t', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.TextField()),
                ('episodes', models.IntegerField()),
                ('avg_runtime', models.IntegerField()),
                ('premiere', models.IntegerField()),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.show')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.IntegerField()),
                ('media_id', models.IntegerField()),
                ('ctype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.credittype')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.IntegerField()),
                ('start_d', models.DateField()),
                ('finish_d', models.DateField()),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='wtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wikitype'),
        ),
    ]
