# Generated by Django 4.2.14 on 2024-07-13 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0002_pagina_pagerels'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wdate', models.DateField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.movie')),
            ],
        ),
    ]
