# Generated by Django 4.2.14 on 2024-07-19 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0004_showwatch_mediawiki'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listname', models.CharField(max_length=500)),
                ('date_created', models.DateField(auto_now=True)),
                ('listinfo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RelBookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
                ('blist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.booklist')),
            ],
        ),
    ]
