# Generated by Django 4.2.14 on 2024-07-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0005_booklist_relbooklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('avance', models.IntegerField(blank=True, default=0)),
                ('fecha_inicio', models.DateField()),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('progreso', models.IntegerField()),
                ('barra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.progressbar')),
            ],
        ),
    ]
