# Generated by Django 4.2.14 on 2024-07-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0006_progressbar_progresslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresslog',
            name='delta_lec',
            field=models.IntegerField(default=0),
        ),
    ]
