# Generated by Django 4.2.14 on 2024-08-22 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0007_progresslog_delta_lec'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonProgressBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avance', models.IntegerField(blank=True, default=0)),
                ('fecha_inicio', models.DateField()),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.season')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('progreso', models.IntegerField()),
                ('delta_lec', models.IntegerField(default=0)),
                ('barra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.seasonprogressbar')),
            ],
        ),
    ]
