# Generated by Django 4.2.14 on 2024-09-11 16:35

from django.db import migrations, models
import django.db.models.deletion
import times.models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0008_seasonprogressbar_seasonprogresslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.movie')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.wiki')),
            ],
        ),
        migrations.CreateModel(
            name='BookMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
    ]
