# Generated by Django 4.2.14 on 2024-10-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0010_moviecredit'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_b', to='times.movie')),
                ('right_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_b', to='times.movie')),
                ('win_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_b', to='times.movie')),
            ],
        ),
        migrations.CreateModel(
            name='BookDuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left_b', to='times.book')),
                ('right_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_b', to='times.book')),
                ('win_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win_b', to='times.book')),
            ],
        ),
    ]
