# Generated by Django 4.2.14 on 2024-12-09 23:58

from django.db import migrations, models
import times.models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0011_movieduel_bookduel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimesMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('imgtype', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=times.models.path_and_name)),
            ],
        ),
    ]
