# Generated by Django 4.2.14 on 2024-12-11 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0012_timesmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=256)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.book')),
            ],
        ),
    ]
