# Generated by Django 4.2.14 on 2024-12-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('times', '0013_booktag'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesmedia',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
